enum {
    kTagBackground = 1,
    kTagMainGameMenuLabel = 2,
	kTagFever = 3,
	kTagLayerDiver = 4,
	kTagLayerDiveFeet = 5,
	kTagRocks = 6,
	kTagRope = 7,
	kTagLabelDiveFeet = 8,
	kTagLabelFever = 9,
	kTagGameSceneLayer = 10,
	kTagMLTitleMain = 11,
	kTagMLTitleOption = 12,

	kTagActionDiverFever = 14,
	kTagLabelScore = 15,
	kTagSprtBackground = 16,
	kTagActionRopeSignal = 17,
	kTagSprtBackgroundProgress = 18,
	kTagSprtForegroundProgress = 19,

	kTagParticleDiverBoost = 20,
	kTagParticleFever = 21,

	kTagForMarinelifes = 777,
	kTagLayerDolphin = 778,
	kTagLayerTurtle = 779,
	kTagLayerSquid = 780,
	kTagLayerStarfish = 781,
	kTagLayerSeahorse = 782,
	kTagLayerMermaid = 783,
	kTagLayerRay = 784,
	kTagLayerJellyfish = 785,
	kTagLayerOrca = 786,
	kTagLayerBrain = 787,
};